checkpoint_1
romanchick8122/TPP2D pull request #1
Opened 2021-03-21 18:06 UTC by romanchick8122

- Архитектура для создания юнитов
- Основа движка игры

2021-03-24 15:50 UTC, linlit requested changes
очень сложно понять, что у тебя происходит, если честно

2021-03-24 15:50 UTC, linlit commented on include/GameLogic/Factory.h
> +class Factory1 : public Factory {
для каждого класса должны быть отдельные .h и .cpp

2021-03-24 15:50 UTC, linlit commented on src/GameLogic/AllFlags.cpp
> +        landscape0->randParameter = 10;
магические константы (то есть те, которые взялись из ниоткуда) - это антипаттерн: https://en.wikipedia.org/wiki/Magic_number_(programming)
лучше создать конфиг файл со всеми нужными константами

2021-03-24 15:50 UTC, linlit commented on src/engine/gameController.cpp
> +                        if (auto obj = dynamic_cast<clickableGameObject*>(*objIt)) {
зачем тебе касты

2021-03-24 15:50 UTC, linlit commented on src/graphics/SFMLFacade.cpp
> +    delete[] vertexArray;
зачем delete, когда есть умные указатели

2021-03-24 15:50 UTC, linlit commented on include/GameLogic/Factory.h
> +    int param3;
who is param1, param2, param3
парам-пам-пам

2021-03-24 15:50 UTC, linlit commented on include/GameLogic/Factory.h
> +    int param3;
и зачем ты создаешь три фабрики-наследника, которые отличаются наличием каких-то непонятных сходу полей param?
задумка как бы хорошая, но в таком случае пока неоправданно. плюс про юнитов тот же вопрос

2021-03-24 15:50 UTC, linlit commented on src/GameLogic/Action.cpp
> +//    squad->center.x += dx;
комменты какие-то затесались

2021-03-24 15:50 UTC, linlit commented on include/GameLogic/Unit.h
> +class TestUnit1 : public Unit {
и прикопаюсь к названию, неужто более говорящего нет?

2021-03-24 15:50 UTC, linlit commented on src/GameLogic/Unit.cpp
> +    allOrders = std::vector<UnitOrder*>(1);
у тебя же даже одно и то же происходит в констукторах всех трех юнитов

2021-03-24 15:50 UTC, linlit commented on include/GameLogic/AllUnits.h
> +    Factory1* TU1_light = new Factory1(100, 1);
у тебя должна быть абстрактная фабрика, зачем ты ее создаешь
и зачем тебе вообще эти 6 созданий нужны

2021-03-24 15:50 UTC, linlit commented on CMakeLists.txt
> +add_executable(TPP2D src/GameLogic/Cell.cpp src/GameLogic/SquadOrder.cpp include/GameLogic/SquadOrder.h src/GameLogic/Action.cpp include/GameLogic/Action.h src/GameLogic/Flag.cpp include/GameLogic/Fl
у тебя же была домашка на cmake, это неверно

2021-03-24 15:50 UTC, linlit commented on include/GameLogic/Factory.h
> +    int param3;
фабрика должна создавать разных юнитов, один из закономерно появляющихся вопросов: почему остальные парамы нельзя нулами оставить?

2021-04-05 18:08 UTC, linlit commented on include/GameLogic/Cell.h
> +    //todo две функции на похуй меняют приватные поля, звучит хуево
ммммм...

2021-04-09 16:54 UTC, bralexx commented on include/GameLogic/Factory.h
> +    int param3;
Это были тестовые юниты (заглушки)
У нас будет много юнитов и есть группы, которые будут отличаться только значениями фиксированного набора параметров. Для таких групп мы будем создавать один класс и одну фабрику (различия будут получаться при создании фабрик, с определенными параметрами)

param это те параметры

здесь одним классом делать можно, но в конечной версии классы будут совсем разными (и функционалом будут отличаться)

короче это наши заглушки и тесты

2021-04-09 16:56 UTC, bralexx commented on src/GameLogic/Action.cpp
> +//    squad->center.x += dx;
упс..

2021-04-09 16:56 UTC, bralexx commented on include/GameLogic/Unit.h
> +class TestUnit1 : public Unit {
заглушки...

2021-04-09 16:57 UTC, bralexx commented on src/GameLogic/Unit.cpp
> +    allOrders = std::vector<UnitOrder*>(1);
заглушки...

2021-04-09 17:05 UTC, bralexx commented on include/GameLogic/AllUnits.h
> +    Factory1* TU1_light = new Factory1(100, 1);
ну тут сама та идея показывается: создаем один класс для всех видов танков, а потом делаем разные фабрики для легких таков, средних и тд (инициализируя параметры (броня, скорость, стоимость))

2021-04-09 17:08 UTC, bralexx commented on CMakeLists.txt
> +add_executable(TPP2D src/GameLogic/Cell.cpp src/GameLogic/SquadOrder.cpp include/GameLogic/SquadOrder.h src/GameLogic/Action.cpp include/GameLogic/Action.h src/GameLogic/Flag.cpp include/GameLogic/Fl
ну вбщ это силайн все сделал
сделал

2021-04-09 17:38 UTC, bralexx commented on include/GameLogic/Cell.h
> +    //todo две функции на похуй меняют приватные поля, звучит хуево
упс

2021-04-09 17:50 UTC, bralexx commented on include/GameLogic/Factory.h
> +class Factory1 : public Factory {
там была другая идея, которая предполагала много классов юнитов и фабрик

но уже другая идея и с файлы норм сделаем

2021-04-14 12:41 UTC, linlit commented on server/main.cpp
> +    //init sockets
инициализация сокетов не должна производиться в мэйне - этот  процесс должен быть скрыт от пользователя

2021-04-14 12:43 UTC, linlit commented on src/graphics/SFMLFacade.cpp
> +    delete[] vertexArray;
это так и не исправлено?

2021-04-14 12:44 UTC, linlit commented on include/GameLogic/Squad/SquadTemplate.h
> +        void addFactory(Factory *, int);
почему сквод добавляет себе фабрику?

2021-04-14 12:45 UTC, linlit commented on include/GameLogic/Units/AllUnits.h
> +    extern std::vector<Factory *> allUnits;
почему поле с юнитами хранит фабрику, а не юнитов?

2021-04-14 12:47 UTC, linlit commented on src/GameLogic/Units/AllUnits.cpp
> +    void setUnits() {
почему это отдельная функция, а не метод класса?

2021-04-14 12:49 UTC, linlit commented on include/GameLogic/Units/Unit.h
> +        void disableOrder();
точно ли это все должно быть публичным?

2021-04-14 12:55 UTC, linlit commented on src/graphics/SFMLFacade.cpp
> +    delete[] vertexArray;
так и неясно, зачем так делать....

2021-04-14 13:41 UTC, romanchick8122 commented on include/GameLogic/Squad/SquadTemplate.h
> +        void addFactory(Factory *, int);
Это не сам сквод, это шаблон сквода, который уже будет собирать готовые скводы при необходимости.

2021-04-14 13:45 UTC, linlit commented on include/GameLogic/Squad/SquadTemplate.h
> +        void addFactory(Factory *, int);
аааа, эвоно как, поняла

2021-04-14 14:04 UTC, bralexx commented on include/GameLogic/Units/AllUnits.h
> +    extern std::vector<Factory *> allUnits;
тип конечные юниты у нас представлены фабриками с определенными параметрами (есть класс танк и куча видов танков (в зависимости от корпусов и пушек). Создавать класс под каждый тип танков больно и мы решили делать просто разные фабрики (каждая производит конкретный подвид танка))
поэтому в allUnits лежат фабрики, но логически это наши конечные юниты

крч мы не знаем как это правильно назвать

2021-04-29 15:13 UTC, merged